/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_25 (coord M15), LPUART1_RXD/J32[2] */
/* Routed pin properties */
#define BOARD_INITLPUARTPINS_LPUART1_RXD_PERIPHERAL                      LPUART1   /*!< Peripheral name */
#define BOARD_INITLPUARTPINS_LPUART1_RXD_SIGNAL                              RXD   /*!< Signal name */

/* GPIO_AD_24 (coord L13), LPUART1_TXD/J31[2] */
/* Routed pin properties */
#define BOARD_INITLPUARTPINS_LPUART1_TXD_PERIPHERAL                      LPUART1   /*!< Peripheral name */
#define BOARD_INITLPUARTPINS_LPUART1_TXD_SIGNAL                              TXD   /*!< Signal name */

/* GPIO_EMC_B2_18 (coord N3), USER_GREEN */
/* Routed pin properties */
#define BOARD_INITLPUARTPINS_USER_GREEN_PERIPHERAL                         GPIO8   /*!< Peripheral name */
#define BOARD_INITLPUARTPINS_USER_GREEN_SIGNAL                           gpio_io   /*!< Signal name */
#define BOARD_INITLPUARTPINS_USER_GREEN_CHANNEL                              28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLPUARTPINS_USER_GREEN_GPIO                               GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITLPUARTPINS_USER_GREEN_GPIO_PIN                             28U   /*!< GPIO pin number */
#define BOARD_INITLPUARTPINS_USER_GREEN_GPIO_PIN_MASK                (1U << 28U)   /*!< GPIO pin mask */

/* GPIO_AD_08 (coord R15), USER_RED */
/* Routed pin properties */
#define BOARD_INITLPUARTPINS_USER_RED_PERIPHERAL                           GPIO9   /*!< Peripheral name */
#define BOARD_INITLPUARTPINS_USER_RED_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITLPUARTPINS_USER_RED_CHANNEL                                 7U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLPUARTPINS_USER_RED_GPIO                                 GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITLPUARTPINS_USER_RED_GPIO_PIN                                7U   /*!< GPIO pin number */
#define BOARD_INITLPUARTPINS_USER_RED_GPIO_PIN_MASK                   (1U << 7U)   /*!< GPIO pin mask */

/* GPIO_AD_10 (coord R17), USER_BLUE */
/* Routed pin properties */
#define BOARD_INITLPUARTPINS_USER_BLUE_PERIPHERAL                          GPIO9   /*!< Peripheral name */
#define BOARD_INITLPUARTPINS_USER_BLUE_SIGNAL                            gpio_io   /*!< Signal name */
#define BOARD_INITLPUARTPINS_USER_BLUE_CHANNEL                                9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLPUARTPINS_USER_BLUE_GPIO                                GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITLPUARTPINS_USER_BLUE_GPIO_PIN                               9U   /*!< GPIO pin number */
#define BOARD_INITLPUARTPINS_USER_BLUE_GPIO_PIN_MASK                  (1U << 9U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLpuartPins(void);              /* Function assigned for the Cortex-M7F */

/* GPIO_AD_29 (coord M17), DISP_POWER */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_DISP_POWER_PERIPHERAL                      GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_DISP_POWER_SIGNAL                        gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_DISP_POWER_CHANNEL                           28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_DISP_POWER_GPIO                            GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_DISP_POWER_GPIO_PIN                          28U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_DISP_POWER_GPIO_PIN_MASK             (1U << 28U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_12 (coord M2), DISP_RST */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_DISP_RST_PERIPHERAL                        GPIO8   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_DISP_RST_SIGNAL                          gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_DISP_RST_CHANNEL                             22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_DISP_RST_GPIO                              GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_DISP_RST_GPIO_PIN                            22U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_DISP_RST_GPIO_PIN_MASK               (1U << 22U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_03 (coord R1), DISP_BL */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_DISP_BL_PERIPHERAL                         GPIO8   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_DISP_BL_SIGNAL                           gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_DISP_BL_CHANNEL                              13U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_DISP_BL_GPIO                               GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_DISP_BL_GPIO_PIN                             13U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_DISP_BL_GPIO_PIN_MASK                (1U << 13U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitMipiPanelPins(void);           /* Function assigned for the Cortex-M7F */

/* GPIO_EMC_B1_40 (coord K1), CAMERA_PWDN */
/* Routed pin properties */
#define BOARD_INITMIPICAMERAPINS_CAMERA_PWDN_PERIPHERAL                    GPIO8   /*!< Peripheral name */
#define BOARD_INITMIPICAMERAPINS_CAMERA_PWDN_SIGNAL                      gpio_io   /*!< Signal name */
#define BOARD_INITMIPICAMERAPINS_CAMERA_PWDN_CHANNEL                          8U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPICAMERAPINS_CAMERA_PWDN_GPIO                          GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPICAMERAPINS_CAMERA_PWDN_GPIO_PIN                         8U   /*!< GPIO pin number */
#define BOARD_INITMIPICAMERAPINS_CAMERA_PWDN_GPIO_PIN_MASK            (1U << 8U)   /*!< GPIO pin mask */

/* GPIO_AD_09 (coord R16), CAMERA_RST */
/* Routed pin properties */
#define BOARD_INITMIPICAMERAPINS_CAMERA_RST_PERIPHERAL                     GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPICAMERAPINS_CAMERA_RST_SIGNAL                       gpio_io   /*!< Signal name */
#define BOARD_INITMIPICAMERAPINS_CAMERA_RST_CHANNEL                           8U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPICAMERAPINS_CAMERA_RST_GPIO                           GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPICAMERAPINS_CAMERA_RST_GPIO_PIN                          8U   /*!< GPIO pin number */
#define BOARD_INITMIPICAMERAPINS_CAMERA_RST_GPIO_PIN_MASK             (1U << 8U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_00 (coord K2), LPI2C2_SCL */
/* Routed pin properties */
#define BOARD_INITMIPICAMERAPINS_LPI2C2_SCL_PERIPHERAL                    LPI2C2   /*!< Peripheral name */
#define BOARD_INITMIPICAMERAPINS_LPI2C2_SCL_SIGNAL                           SCL   /*!< Signal name */

/* GPIO_EMC_B2_01 (coord K4), LPI2C2_SDA */
/* Routed pin properties */
#define BOARD_INITMIPICAMERAPINS_LPI2C2_SDA_PERIPHERAL                    LPI2C2   /*!< Peripheral name */
#define BOARD_INITMIPICAMERAPINS_LPI2C2_SDA_SIGNAL                           SDA   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitMipiCameraPins(void);          /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
